// automatically generated by rust-bindgen 0.72.1

pub const __bool_true_false_are_defined: u32 = 1;
pub const true_: u32 = 1;
pub const false_: u32 = 0;
pub struct CoolProp;

unsafe extern "C-unwind" {
    fn Props1SI(FluidName: *const ::core::ffi::c_char, Output: *const ::core::ffi::c_char) -> f64;
    fn Props1SImulti(
        Outputs: *const ::core::ffi::c_char,
        backend: *mut ::core::ffi::c_char,
        FluidNames: *const ::core::ffi::c_char,
        fractions: *const f64,
        length_fractions: ::core::ffi::c_long,
        result: *mut f64,
        resdim1: *mut ::core::ffi::c_long,
    );
    fn PropsSI(
        Output: *const ::core::ffi::c_char,
        Name1: *const ::core::ffi::c_char,
        Prop1: f64,
        Name2: *const ::core::ffi::c_char,
        Prop2: f64,
        FluidName: *const ::core::ffi::c_char,
    ) -> f64;
    fn PropsSImulti(
        Outputs: *const ::core::ffi::c_char,
        Name1: *const ::core::ffi::c_char,
        Prop1: *mut f64,
        size_Prop1: ::core::ffi::c_long,
        Name2: *const ::core::ffi::c_char,
        Prop2: *mut f64,
        size_Prop2: ::core::ffi::c_long,
        backend: *mut ::core::ffi::c_char,
        FluidNames: *const ::core::ffi::c_char,
        fractions: *const f64,
        length_fractions: ::core::ffi::c_long,
        result: *mut f64,
        resdim1: *mut ::core::ffi::c_long,
        resdim2: *mut ::core::ffi::c_long,
    );
    fn PhaseSI(
        Name1: *const ::core::ffi::c_char,
        Prop1: f64,
        Name2: *const ::core::ffi::c_char,
        Prop2: f64,
        FluidName: *const ::core::ffi::c_char,
        phase: *mut ::core::ffi::c_char,
        n: ::core::ffi::c_int,
    ) -> ::core::ffi::c_long;
    fn get_global_param_string(
        param: *const ::core::ffi::c_char,
        Output: *mut ::core::ffi::c_char,
        n: ::core::ffi::c_int,
    ) -> ::core::ffi::c_long;
    fn get_parameter_information_string(
        param: *const ::core::ffi::c_char,
        Output: *mut ::core::ffi::c_char,
        n: ::core::ffi::c_int,
    ) -> ::core::ffi::c_long;
    fn get_fluid_param_string(
        fluid: *const ::core::ffi::c_char,
        param: *const ::core::ffi::c_char,
        Output: *mut ::core::ffi::c_char,
        n: ::core::ffi::c_int,
    ) -> ::core::ffi::c_long;
    fn get_fluid_param_string_len(
        fluid: *const ::core::ffi::c_char,
        param: *const ::core::ffi::c_char,
    ) -> ::core::ffi::c_long;
    fn set_config_string(key: *const ::core::ffi::c_char, val: *const ::core::ffi::c_char);
    fn set_config_double(key: *const ::core::ffi::c_char, val: f64);
    fn set_config_bool(key: *const ::core::ffi::c_char, val: bool);
    fn set_departure_functions(
        string_data: *const ::core::ffi::c_char,
        errcode: *mut ::core::ffi::c_long,
        message_buffer: *mut ::core::ffi::c_char,
        buffer_length: ::core::ffi::c_long,
    );
    fn set_reference_stateS(
        Ref: *const ::core::ffi::c_char,
        reference_state: *const ::core::ffi::c_char,
    ) -> ::core::ffi::c_int;
    fn set_reference_stateD(
        Ref: *const ::core::ffi::c_char,
        T: f64,
        rhomolar: f64,
        hmolar0: f64,
        smolar0: f64,
    ) -> ::core::ffi::c_int;
    fn propssi_(
        Output: *const ::core::ffi::c_char,
        Name1: *const ::core::ffi::c_char,
        Prop1: *const f64,
        Name2: *const ::core::ffi::c_char,
        Prop2: *const f64,
        FluidName: *const ::core::ffi::c_char,
        output: *mut f64,
    );
    fn F2K(T_F: f64) -> f64;
    fn K2F(T_K: f64) -> f64;
    fn get_param_index(param: *const ::core::ffi::c_char) -> ::core::ffi::c_long;
    fn get_input_pair_index(pair: *const ::core::ffi::c_char) -> ::core::ffi::c_long;
    fn redirect_stdout(file: *const ::core::ffi::c_char) -> ::core::ffi::c_long;
    fn get_debug_level() -> ::core::ffi::c_int;
    fn set_debug_level(level: ::core::ffi::c_int);
    fn saturation_ancillary(
        fluid_name: *const ::core::ffi::c_char,
        output: *const ::core::ffi::c_char,
        Q: ::core::ffi::c_int,
        input: *const ::core::ffi::c_char,
        value: f64,
    ) -> f64;
    fn HAPropsSI(
        Output: *const ::core::ffi::c_char,
        Name1: *const ::core::ffi::c_char,
        Prop1: f64,
        Name2: *const ::core::ffi::c_char,
        Prop2: f64,
        Name3: *const ::core::ffi::c_char,
        Prop3: f64,
    ) -> f64;
    fn cair_sat(T: f64) -> f64;
    fn hapropssi_(
        Output: *const ::core::ffi::c_char,
        Name1: *const ::core::ffi::c_char,
        Prop1: *const f64,
        Name2: *const ::core::ffi::c_char,
        Prop2: *const f64,
        Name3: *const ::core::ffi::c_char,
        Prop3: *const f64,
        output: *mut f64,
    );
    fn HAProps(
        Output: *const ::core::ffi::c_char,
        Name1: *const ::core::ffi::c_char,
        Prop1: f64,
        Name2: *const ::core::ffi::c_char,
        Prop2: f64,
        Name3: *const ::core::ffi::c_char,
        Prop3: f64,
    ) -> f64;
    fn haprops_(
        Output: *const ::core::ffi::c_char,
        Name1: *const ::core::ffi::c_char,
        Prop1: *const f64,
        Name2: *const ::core::ffi::c_char,
        Prop2: *const f64,
        Name3: *const ::core::ffi::c_char,
        Prop3: *const f64,
        output: *mut f64,
    );
    fn AbstractState_factory(
        backend: *const ::core::ffi::c_char,
        fluids: *const ::core::ffi::c_char,
        errcode: *mut ::core::ffi::c_long,
        message_buffer: *mut ::core::ffi::c_char,
        buffer_length: ::core::ffi::c_long,
    ) -> ::core::ffi::c_long;
    fn AbstractState_fluid_names(
        handle: ::core::ffi::c_long,
        fluids: *mut ::core::ffi::c_char,
        errcode: *mut ::core::ffi::c_long,
        message_buffer: *mut ::core::ffi::c_char,
        buffer_length: ::core::ffi::c_long,
    );
    fn AbstractState_free(
        handle: ::core::ffi::c_long,
        errcode: *mut ::core::ffi::c_long,
        message_buffer: *mut ::core::ffi::c_char,
        buffer_length: ::core::ffi::c_long,
    );
    fn AbstractState_set_fractions(
        handle: ::core::ffi::c_long,
        fractions: *const f64,
        N: ::core::ffi::c_long,
        errcode: *mut ::core::ffi::c_long,
        message_buffer: *mut ::core::ffi::c_char,
        buffer_length: ::core::ffi::c_long,
    );
    fn AbstractState_get_mole_fractions(
        handle: ::core::ffi::c_long,
        fractions: *mut f64,
        maxN: ::core::ffi::c_long,
        N: *mut ::core::ffi::c_long,
        errcode: *mut ::core::ffi::c_long,
        message_buffer: *mut ::core::ffi::c_char,
        buffer_length: ::core::ffi::c_long,
    );
    fn AbstractState_get_mole_fractions_satState(
        handle: ::core::ffi::c_long,
        saturated_state: *const ::core::ffi::c_char,
        fractions: *mut f64,
        maxN: ::core::ffi::c_long,
        N: *mut ::core::ffi::c_long,
        errcode: *mut ::core::ffi::c_long,
        message_buffer: *mut ::core::ffi::c_char,
        buffer_length: ::core::ffi::c_long,
    );
    fn AbstractState_get_fugacity(
        handle: ::core::ffi::c_long,
        i: ::core::ffi::c_long,
        errcode: *mut ::core::ffi::c_long,
        message_buffer: *mut ::core::ffi::c_char,
        buffer_length: ::core::ffi::c_long,
    ) -> f64;
    fn AbstractState_get_fugacity_coefficient(
        handle: ::core::ffi::c_long,
        i: ::core::ffi::c_long,
        errcode: *mut ::core::ffi::c_long,
        message_buffer: *mut ::core::ffi::c_char,
        buffer_length: ::core::ffi::c_long,
    ) -> f64;
    fn AbstractState_update(
        handle: ::core::ffi::c_long,
        input_pair: ::core::ffi::c_long,
        value1: f64,
        value2: f64,
        errcode: *mut ::core::ffi::c_long,
        message_buffer: *mut ::core::ffi::c_char,
        buffer_length: ::core::ffi::c_long,
    );
    fn AbstractState_specify_phase(
        handle: ::core::ffi::c_long,
        phase: *const ::core::ffi::c_char,
        errcode: *mut ::core::ffi::c_long,
        message_buffer: *mut ::core::ffi::c_char,
        buffer_length: ::core::ffi::c_long,
    );
    fn AbstractState_unspecify_phase(
        handle: ::core::ffi::c_long,
        errcode: *mut ::core::ffi::c_long,
        message_buffer: *mut ::core::ffi::c_char,
        buffer_length: ::core::ffi::c_long,
    );
    fn AbstractState_keyed_output(
        handle: ::core::ffi::c_long,
        param: ::core::ffi::c_long,
        errcode: *mut ::core::ffi::c_long,
        message_buffer: *mut ::core::ffi::c_char,
        buffer_length: ::core::ffi::c_long,
    ) -> f64;
    fn AbstractState_first_saturation_deriv(
        handle: ::core::ffi::c_long,
        Of: ::core::ffi::c_long,
        Wrt: ::core::ffi::c_long,
        errcode: *mut ::core::ffi::c_long,
        message_buffer: *mut ::core::ffi::c_char,
        buffer_length: ::core::ffi::c_long,
    ) -> f64;
    fn AbstractState_first_partial_deriv(
        handle: ::core::ffi::c_long,
        Of: ::core::ffi::c_long,
        Wrt: ::core::ffi::c_long,
        Constant: ::core::ffi::c_long,
        errcode: *mut ::core::ffi::c_long,
        message_buffer: *mut ::core::ffi::c_char,
        buffer_length: ::core::ffi::c_long,
    ) -> f64;
    fn AbstractState_second_two_phase_deriv(
        handle: ::core::ffi::c_long,
        Of1: ::core::ffi::c_long,
        Wrt1: ::core::ffi::c_long,
        Constant1: ::core::ffi::c_long,
        Wrt2: ::core::ffi::c_long,
        Constant2: ::core::ffi::c_long,
        errcode: *mut ::core::ffi::c_long,
        message_buffer: *mut ::core::ffi::c_char,
        buffer_length: ::core::ffi::c_long,
    ) -> f64;
    fn AbstractState_second_partial_deriv(
        handle: ::core::ffi::c_long,
        Of1: ::core::ffi::c_long,
        Wrt1: ::core::ffi::c_long,
        Constant1: ::core::ffi::c_long,
        Wrt2: ::core::ffi::c_long,
        Constant2: ::core::ffi::c_long,
        errcode: *mut ::core::ffi::c_long,
        message_buffer: *mut ::core::ffi::c_char,
        buffer_length: ::core::ffi::c_long,
    ) -> f64;
    fn AbstractState_first_two_phase_deriv_splined(
        handle: ::core::ffi::c_long,
        Of: ::core::ffi::c_long,
        Wrt: ::core::ffi::c_long,
        Constant: ::core::ffi::c_long,
        x_end: f64,
        errcode: *mut ::core::ffi::c_long,
        message_buffer: *mut ::core::ffi::c_char,
        buffer_length: ::core::ffi::c_long,
    ) -> f64;
    fn AbstractState_first_two_phase_deriv(
        handle: ::core::ffi::c_long,
        Of: ::core::ffi::c_long,
        Wrt: ::core::ffi::c_long,
        Constant: ::core::ffi::c_long,
        errcode: *mut ::core::ffi::c_long,
        message_buffer: *mut ::core::ffi::c_char,
        buffer_length: ::core::ffi::c_long,
    ) -> f64;
    fn AbstractState_update_and_common_out(
        handle: ::core::ffi::c_long,
        input_pair: ::core::ffi::c_long,
        value1: *const f64,
        value2: *const f64,
        length: ::core::ffi::c_long,
        T: *mut f64,
        p: *mut f64,
        rhomolar: *mut f64,
        hmolar: *mut f64,
        smolar: *mut f64,
        errcode: *mut ::core::ffi::c_long,
        message_buffer: *mut ::core::ffi::c_char,
        buffer_length: ::core::ffi::c_long,
    );
    fn AbstractState_update_and_1_out(
        handle: ::core::ffi::c_long,
        input_pair: ::core::ffi::c_long,
        value1: *const f64,
        value2: *const f64,
        length: ::core::ffi::c_long,
        output: ::core::ffi::c_long,
        out: *mut f64,
        errcode: *mut ::core::ffi::c_long,
        message_buffer: *mut ::core::ffi::c_char,
        buffer_length: ::core::ffi::c_long,
    );
    fn AbstractState_update_and_5_out(
        handle: ::core::ffi::c_long,
        input_pair: ::core::ffi::c_long,
        value1: *const f64,
        value2: *const f64,
        length: ::core::ffi::c_long,
        outputs: *mut ::core::ffi::c_long,
        out1: *mut f64,
        out2: *mut f64,
        out3: *mut f64,
        out4: *mut f64,
        out5: *mut f64,
        errcode: *mut ::core::ffi::c_long,
        message_buffer: *mut ::core::ffi::c_char,
        buffer_length: ::core::ffi::c_long,
    );
    fn AbstractState_set_binary_interaction_double(
        handle: ::core::ffi::c_long,
        i: ::core::ffi::c_long,
        j: ::core::ffi::c_long,
        parameter: *const ::core::ffi::c_char,
        value: f64,
        errcode: *mut ::core::ffi::c_long,
        message_buffer: *mut ::core::ffi::c_char,
        buffer_length: ::core::ffi::c_long,
    );
    fn AbstractState_set_cubic_alpha_C(
        handle: ::core::ffi::c_long,
        i: ::core::ffi::c_long,
        parameter: *const ::core::ffi::c_char,
        c1: f64,
        c2: f64,
        c3: f64,
        errcode: *mut ::core::ffi::c_long,
        message_buffer: *mut ::core::ffi::c_char,
        buffer_length: ::core::ffi::c_long,
    );
    fn AbstractState_set_fluid_parameter_double(
        handle: ::core::ffi::c_long,
        i: ::core::ffi::c_long,
        parameter: *const ::core::ffi::c_char,
        value: f64,
        errcode: *mut ::core::ffi::c_long,
        message_buffer: *mut ::core::ffi::c_char,
        buffer_length: ::core::ffi::c_long,
    );
    fn AbstractState_build_phase_envelope(
        handle: ::core::ffi::c_long,
        level: *const ::core::ffi::c_char,
        errcode: *mut ::core::ffi::c_long,
        message_buffer: *mut ::core::ffi::c_char,
        buffer_length: ::core::ffi::c_long,
    );
    fn AbstractState_get_phase_envelope_data(
        handle: ::core::ffi::c_long,
        length: ::core::ffi::c_long,
        T: *mut f64,
        p: *mut f64,
        rhomolar_vap: *mut f64,
        rhomolar_liq: *mut f64,
        x: *mut f64,
        y: *mut f64,
        errcode: *mut ::core::ffi::c_long,
        message_buffer: *mut ::core::ffi::c_char,
        buffer_length: ::core::ffi::c_long,
    );
    fn AbstractState_get_phase_envelope_data_checkedMemory(
        handle: ::core::ffi::c_long,
        length: ::core::ffi::c_long,
        maxComponents: ::core::ffi::c_long,
        T: *mut f64,
        p: *mut f64,
        rhomolar_vap: *mut f64,
        rhomolar_liq: *mut f64,
        x: *mut f64,
        y: *mut f64,
        actual_length: *mut ::core::ffi::c_long,
        actual_components: *mut ::core::ffi::c_long,
        errcode: *mut ::core::ffi::c_long,
        message_buffer: *mut ::core::ffi::c_char,
        buffer_length: ::core::ffi::c_long,
    );
    fn AbstractState_build_spinodal(
        handle: ::core::ffi::c_long,
        errcode: *mut ::core::ffi::c_long,
        message_buffer: *mut ::core::ffi::c_char,
        buffer_length: ::core::ffi::c_long,
    );
    fn AbstractState_get_spinodal_data(
        handle: ::core::ffi::c_long,
        length: ::core::ffi::c_long,
        tau: *mut f64,
        delta: *mut f64,
        M1: *mut f64,
        errcode: *mut ::core::ffi::c_long,
        message_buffer: *mut ::core::ffi::c_char,
        buffer_length: ::core::ffi::c_long,
    );
    fn AbstractState_all_critical_points(
        handle: ::core::ffi::c_long,
        length: ::core::ffi::c_long,
        T: *mut f64,
        p: *mut f64,
        rhomolar: *mut f64,
        stable: *mut ::core::ffi::c_long,
        errcode: *mut ::core::ffi::c_long,
        message_buffer: *mut ::core::ffi::c_char,
        buffer_length: ::core::ffi::c_long,
    );
    fn AbstractState_keyed_output_satState(
        handle: ::core::ffi::c_long,
        saturated_state: *const ::core::ffi::c_char,
        param: ::core::ffi::c_long,
        errcode: *mut ::core::ffi::c_long,
        message_buffer: *mut ::core::ffi::c_char,
        buffer_length: ::core::ffi::c_long,
    ) -> f64;
    fn AbstractState_backend_name(
        handle: ::core::ffi::c_long,
        backend: *mut ::core::ffi::c_char,
        errcode: *mut ::core::ffi::c_long,
        message_buffer: *mut ::core::ffi::c_char,
        buffer_length: ::core::ffi::c_long,
    );
    fn AbstractState_fluid_param_string(
        handle: ::core::ffi::c_long,
        param: *const ::core::ffi::c_char,
        return_buffer: *mut ::core::ffi::c_char,
        return_buffer_length: ::core::ffi::c_long,
        errcode: *mut ::core::ffi::c_long,
        message_buffer: *mut ::core::ffi::c_char,
        buffer_length: ::core::ffi::c_long,
    );
    fn AbstractState_phase(
        handle: ::core::ffi::c_long,
        errcode: *mut ::core::ffi::c_long,
        message_buffer: *mut ::core::ffi::c_char,
        buffer_length: ::core::ffi::c_long,
    ) -> ::core::ffi::c_int;
    fn AbstractState_saturated_liquid_keyed_output(
        handle: ::core::ffi::c_long,
        param: ::core::ffi::c_long,
        errcode: *mut ::core::ffi::c_long,
        message_buffer: *mut ::core::ffi::c_char,
        buffer_length: ::core::ffi::c_long,
    ) -> f64;
    fn AbstractState_saturated_vapor_keyed_output(
        handle: ::core::ffi::c_long,
        param: ::core::ffi::c_long,
        errcode: *mut ::core::ffi::c_long,
        message_buffer: *mut ::core::ffi::c_char,
        buffer_length: ::core::ffi::c_long,
    ) -> f64;
    fn add_fluids_as_JSON(
        backend: *const ::core::ffi::c_char,
        fluidstring: *const ::core::ffi::c_char,
        errcode: *mut ::core::ffi::c_long,
        message_buffer: *mut ::core::ffi::c_char,
        buffer_length: ::core::ffi::c_long,
    );
    fn C_is_valid_fluid_string(fluidName: *const ::core::ffi::c_char) -> ::core::ffi::c_int;
    fn C_extract_backend(
        fluid_string: *const ::core::ffi::c_char,
        backend: *mut ::core::ffi::c_char,
        backend_length: ::core::ffi::c_long,
        fluid: *mut ::core::ffi::c_char,
        fluid_length: ::core::ffi::c_long,
    ) -> ::core::ffi::c_int;
}

impl CoolProp {
    pub unsafe fn new(_path: &str) -> Result<Self, ::core::convert::Infallible> {
        Ok(Self)
    }

    pub unsafe fn Props1SI(
        &self,
        FluidName: *const ::core::ffi::c_char,
        Output: *const ::core::ffi::c_char,
    ) -> f64 {
        Props1SI(FluidName, Output)
    }

    pub unsafe fn Props1SImulti(
        &self,
        Outputs: *const ::core::ffi::c_char,
        backend: *mut ::core::ffi::c_char,
        FluidNames: *const ::core::ffi::c_char,
        fractions: *const f64,
        length_fractions: ::core::ffi::c_long,
        result: *mut f64,
        resdim1: *mut ::core::ffi::c_long,
    ) {
        Props1SImulti(Outputs, backend, FluidNames, fractions, length_fractions, result, resdim1)
    }

    pub unsafe fn PropsSI(
        &self,
        Output: *const ::core::ffi::c_char,
        Name1: *const ::core::ffi::c_char,
        Prop1: f64,
        Name2: *const ::core::ffi::c_char,
        Prop2: f64,
        FluidName: *const ::core::ffi::c_char,
    ) -> f64 {
        PropsSI(Output, Name1, Prop1, Name2, Prop2, FluidName)
    }

    pub unsafe fn PropsSImulti(
        &self,
        Outputs: *const ::core::ffi::c_char,
        Name1: *const ::core::ffi::c_char,
        Prop1: *mut f64,
        size_Prop1: ::core::ffi::c_long,
        Name2: *const ::core::ffi::c_char,
        Prop2: *mut f64,
        size_Prop2: ::core::ffi::c_long,
        backend: *mut ::core::ffi::c_char,
        FluidNames: *const ::core::ffi::c_char,
        fractions: *const f64,
        length_fractions: ::core::ffi::c_long,
        result: *mut f64,
        resdim1: *mut ::core::ffi::c_long,
        resdim2: *mut ::core::ffi::c_long,
    ) {
        PropsSImulti(
            Outputs,
            Name1,
            Prop1,
            size_Prop1,
            Name2,
            Prop2,
            size_Prop2,
            backend,
            FluidNames,
            fractions,
            length_fractions,
            result,
            resdim1,
            resdim2,
        )
    }

    pub unsafe fn PhaseSI(
        &self,
        Name1: *const ::core::ffi::c_char,
        Prop1: f64,
        Name2: *const ::core::ffi::c_char,
        Prop2: f64,
        FluidName: *const ::core::ffi::c_char,
        phase: *mut ::core::ffi::c_char,
        n: ::core::ffi::c_int,
    ) -> ::core::ffi::c_long {
        PhaseSI(Name1, Prop1, Name2, Prop2, FluidName, phase, n)
    }

    pub unsafe fn get_global_param_string(
        &self,
        param: *const ::core::ffi::c_char,
        Output: *mut ::core::ffi::c_char,
        n: ::core::ffi::c_int,
    ) -> ::core::ffi::c_long {
        get_global_param_string(param, Output, n)
    }

    pub unsafe fn get_parameter_information_string(
        &self,
        param: *const ::core::ffi::c_char,
        Output: *mut ::core::ffi::c_char,
        n: ::core::ffi::c_int,
    ) -> ::core::ffi::c_long {
        get_parameter_information_string(param, Output, n)
    }

    pub unsafe fn get_fluid_param_string(
        &self,
        fluid: *const ::core::ffi::c_char,
        param: *const ::core::ffi::c_char,
        Output: *mut ::core::ffi::c_char,
        n: ::core::ffi::c_int,
    ) -> ::core::ffi::c_long {
        get_fluid_param_string(fluid, param, Output, n)
    }

    pub unsafe fn get_fluid_param_string_len(
        &self,
        fluid: *const ::core::ffi::c_char,
        param: *const ::core::ffi::c_char,
    ) -> ::core::ffi::c_long {
        get_fluid_param_string_len(fluid, param)
    }

    pub unsafe fn set_config_string(
        &self,
        key: *const ::core::ffi::c_char,
        val: *const ::core::ffi::c_char,
    ) {
        set_config_string(key, val)
    }

    pub unsafe fn set_config_double(&self, key: *const ::core::ffi::c_char, val: f64) {
        set_config_double(key, val)
    }

    pub unsafe fn set_config_bool(&self, key: *const ::core::ffi::c_char, val: bool) {
        set_config_bool(key, val)
    }

    pub unsafe fn set_departure_functions(
        &self,
        string_data: *const ::core::ffi::c_char,
        errcode: *mut ::core::ffi::c_long,
        message_buffer: *mut ::core::ffi::c_char,
        buffer_length: ::core::ffi::c_long,
    ) {
        set_departure_functions(string_data, errcode, message_buffer, buffer_length)
    }

    pub unsafe fn set_reference_stateS(
        &self,
        Ref: *const ::core::ffi::c_char,
        reference_state: *const ::core::ffi::c_char,
    ) -> ::core::ffi::c_int {
        set_reference_stateS(Ref, reference_state)
    }

    pub unsafe fn set_reference_stateD(
        &self,
        Ref: *const ::core::ffi::c_char,
        T: f64,
        rhomolar: f64,
        hmolar0: f64,
        smolar0: f64,
    ) -> ::core::ffi::c_int {
        set_reference_stateD(Ref, T, rhomolar, hmolar0, smolar0)
    }

    pub unsafe fn propssi_(
        &self,
        Output: *const ::core::ffi::c_char,
        Name1: *const ::core::ffi::c_char,
        Prop1: *const f64,
        Name2: *const ::core::ffi::c_char,
        Prop2: *const f64,
        FluidName: *const ::core::ffi::c_char,
        output: *mut f64,
    ) {
        propssi_(Output, Name1, Prop1, Name2, Prop2, FluidName, output)
    }

    pub unsafe fn F2K(&self, T_F: f64) -> f64 {
        F2K(T_F)
    }

    pub unsafe fn K2F(&self, T_K: f64) -> f64 {
        K2F(T_K)
    }

    pub unsafe fn get_param_index(&self, param: *const ::core::ffi::c_char) -> ::core::ffi::c_long {
        get_param_index(param)
    }

    pub unsafe fn get_input_pair_index(
        &self,
        pair: *const ::core::ffi::c_char,
    ) -> ::core::ffi::c_long {
        get_input_pair_index(pair)
    }

    pub unsafe fn redirect_stdout(&self, file: *const ::core::ffi::c_char) -> ::core::ffi::c_long {
        redirect_stdout(file)
    }

    pub unsafe fn get_debug_level(&self) -> ::core::ffi::c_int {
        get_debug_level()
    }

    pub unsafe fn set_debug_level(&self, level: ::core::ffi::c_int) {
        set_debug_level(level)
    }

    pub unsafe fn saturation_ancillary(
        &self,
        fluid_name: *const ::core::ffi::c_char,
        output: *const ::core::ffi::c_char,
        Q: ::core::ffi::c_int,
        input: *const ::core::ffi::c_char,
        value: f64,
    ) -> f64 {
        saturation_ancillary(fluid_name, output, Q, input, value)
    }

    pub unsafe fn HAPropsSI(
        &self,
        Output: *const ::core::ffi::c_char,
        Name1: *const ::core::ffi::c_char,
        Prop1: f64,
        Name2: *const ::core::ffi::c_char,
        Prop2: f64,
        Name3: *const ::core::ffi::c_char,
        Prop3: f64,
    ) -> f64 {
        HAPropsSI(Output, Name1, Prop1, Name2, Prop2, Name3, Prop3)
    }

    pub unsafe fn cair_sat(&self, T: f64) -> f64 {
        cair_sat(T)
    }

    pub unsafe fn hapropssi_(
        &self,
        Output: *const ::core::ffi::c_char,
        Name1: *const ::core::ffi::c_char,
        Prop1: *const f64,
        Name2: *const ::core::ffi::c_char,
        Prop2: *const f64,
        Name3: *const ::core::ffi::c_char,
        Prop3: *const f64,
        output: *mut f64,
    ) {
        hapropssi_(Output, Name1, Prop1, Name2, Prop2, Name3, Prop3, output)
    }

    pub unsafe fn HAProps(
        &self,
        Output: *const ::core::ffi::c_char,
        Name1: *const ::core::ffi::c_char,
        Prop1: f64,
        Name2: *const ::core::ffi::c_char,
        Prop2: f64,
        Name3: *const ::core::ffi::c_char,
        Prop3: f64,
    ) -> f64 {
        HAProps(Output, Name1, Prop1, Name2, Prop2, Name3, Prop3)
    }

    pub unsafe fn haprops_(
        &self,
        Output: *const ::core::ffi::c_char,
        Name1: *const ::core::ffi::c_char,
        Prop1: *const f64,
        Name2: *const ::core::ffi::c_char,
        Prop2: *const f64,
        Name3: *const ::core::ffi::c_char,
        Prop3: *const f64,
        output: *mut f64,
    ) {
        haprops_(Output, Name1, Prop1, Name2, Prop2, Name3, Prop3, output)
    }

    pub unsafe fn AbstractState_factory(
        &self,
        backend: *const ::core::ffi::c_char,
        fluids: *const ::core::ffi::c_char,
        errcode: *mut ::core::ffi::c_long,
        message_buffer: *mut ::core::ffi::c_char,
        buffer_length: ::core::ffi::c_long,
    ) -> ::core::ffi::c_long {
        AbstractState_factory(backend, fluids, errcode, message_buffer, buffer_length)
    }

    pub unsafe fn AbstractState_fluid_names(
        &self,
        handle: ::core::ffi::c_long,
        fluids: *mut ::core::ffi::c_char,
        errcode: *mut ::core::ffi::c_long,
        message_buffer: *mut ::core::ffi::c_char,
        buffer_length: ::core::ffi::c_long,
    ) {
        AbstractState_fluid_names(handle, fluids, errcode, message_buffer, buffer_length)
    }

    pub unsafe fn AbstractState_free(
        &self,
        handle: ::core::ffi::c_long,
        errcode: *mut ::core::ffi::c_long,
        message_buffer: *mut ::core::ffi::c_char,
        buffer_length: ::core::ffi::c_long,
    ) {
        AbstractState_free(handle, errcode, message_buffer, buffer_length)
    }

    pub unsafe fn AbstractState_set_fractions(
        &self,
        handle: ::core::ffi::c_long,
        fractions: *const f64,
        N: ::core::ffi::c_long,
        errcode: *mut ::core::ffi::c_long,
        message_buffer: *mut ::core::ffi::c_char,
        buffer_length: ::core::ffi::c_long,
    ) {
        AbstractState_set_fractions(handle, fractions, N, errcode, message_buffer, buffer_length)
    }

    pub unsafe fn AbstractState_get_mole_fractions(
        &self,
        handle: ::core::ffi::c_long,
        fractions: *mut f64,
        maxN: ::core::ffi::c_long,
        N: *mut ::core::ffi::c_long,
        errcode: *mut ::core::ffi::c_long,
        message_buffer: *mut ::core::ffi::c_char,
        buffer_length: ::core::ffi::c_long,
    ) {
        AbstractState_get_mole_fractions(
            handle,
            fractions,
            maxN,
            N,
            errcode,
            message_buffer,
            buffer_length,
        )
    }

    pub unsafe fn AbstractState_get_mole_fractions_satState(
        &self,
        handle: ::core::ffi::c_long,
        saturated_state: *const ::core::ffi::c_char,
        fractions: *mut f64,
        maxN: ::core::ffi::c_long,
        N: *mut ::core::ffi::c_long,
        errcode: *mut ::core::ffi::c_long,
        message_buffer: *mut ::core::ffi::c_char,
        buffer_length: ::core::ffi::c_long,
    ) {
        AbstractState_get_mole_fractions_satState(
            handle,
            saturated_state,
            fractions,
            maxN,
            N,
            errcode,
            message_buffer,
            buffer_length,
        )
    }

    pub unsafe fn AbstractState_get_fugacity(
        &self,
        handle: ::core::ffi::c_long,
        i: ::core::ffi::c_long,
        errcode: *mut ::core::ffi::c_long,
        message_buffer: *mut ::core::ffi::c_char,
        buffer_length: ::core::ffi::c_long,
    ) -> f64 {
        AbstractState_get_fugacity(handle, i, errcode, message_buffer, buffer_length)
    }

    pub unsafe fn AbstractState_get_fugacity_coefficient(
        &self,
        handle: ::core::ffi::c_long,
        i: ::core::ffi::c_long,
        errcode: *mut ::core::ffi::c_long,
        message_buffer: *mut ::core::ffi::c_char,
        buffer_length: ::core::ffi::c_long,
    ) -> f64 {
        AbstractState_get_fugacity_coefficient(handle, i, errcode, message_buffer, buffer_length)
    }

    pub unsafe fn AbstractState_update(
        &self,
        handle: ::core::ffi::c_long,
        input_pair: ::core::ffi::c_long,
        value1: f64,
        value2: f64,
        errcode: *mut ::core::ffi::c_long,
        message_buffer: *mut ::core::ffi::c_char,
        buffer_length: ::core::ffi::c_long,
    ) {
        AbstractState_update(
            handle,
            input_pair,
            value1,
            value2,
            errcode,
            message_buffer,
            buffer_length,
        )
    }

    pub unsafe fn AbstractState_specify_phase(
        &self,
        handle: ::core::ffi::c_long,
        phase: *const ::core::ffi::c_char,
        errcode: *mut ::core::ffi::c_long,
        message_buffer: *mut ::core::ffi::c_char,
        buffer_length: ::core::ffi::c_long,
    ) {
        AbstractState_specify_phase(handle, phase, errcode, message_buffer, buffer_length)
    }

    pub unsafe fn AbstractState_unspecify_phase(
        &self,
        handle: ::core::ffi::c_long,
        errcode: *mut ::core::ffi::c_long,
        message_buffer: *mut ::core::ffi::c_char,
        buffer_length: ::core::ffi::c_long,
    ) {
        AbstractState_unspecify_phase(handle, errcode, message_buffer, buffer_length)
    }

    pub unsafe fn AbstractState_keyed_output(
        &self,
        handle: ::core::ffi::c_long,
        param: ::core::ffi::c_long,
        errcode: *mut ::core::ffi::c_long,
        message_buffer: *mut ::core::ffi::c_char,
        buffer_length: ::core::ffi::c_long,
    ) -> f64 {
        AbstractState_keyed_output(handle, param, errcode, message_buffer, buffer_length)
    }

    pub unsafe fn AbstractState_first_saturation_deriv(
        &self,
        handle: ::core::ffi::c_long,
        Of: ::core::ffi::c_long,
        Wrt: ::core::ffi::c_long,
        errcode: *mut ::core::ffi::c_long,
        message_buffer: *mut ::core::ffi::c_char,
        buffer_length: ::core::ffi::c_long,
    ) -> f64 {
        AbstractState_first_saturation_deriv(
            handle,
            Of,
            Wrt,
            errcode,
            message_buffer,
            buffer_length,
        )
    }

    pub unsafe fn AbstractState_first_partial_deriv(
        &self,
        handle: ::core::ffi::c_long,
        Of: ::core::ffi::c_long,
        Wrt: ::core::ffi::c_long,
        Constant: ::core::ffi::c_long,
        errcode: *mut ::core::ffi::c_long,
        message_buffer: *mut ::core::ffi::c_char,
        buffer_length: ::core::ffi::c_long,
    ) -> f64 {
        AbstractState_first_partial_deriv(
            handle,
            Of,
            Wrt,
            Constant,
            errcode,
            message_buffer,
            buffer_length,
        )
    }

    pub unsafe fn AbstractState_second_two_phase_deriv(
        &self,
        handle: ::core::ffi::c_long,
        Of1: ::core::ffi::c_long,
        Wrt1: ::core::ffi::c_long,
        Constant1: ::core::ffi::c_long,
        Wrt2: ::core::ffi::c_long,
        Constant2: ::core::ffi::c_long,
        errcode: *mut ::core::ffi::c_long,
        message_buffer: *mut ::core::ffi::c_char,
        buffer_length: ::core::ffi::c_long,
    ) -> f64 {
        AbstractState_second_two_phase_deriv(
            handle,
            Of1,
            Wrt1,
            Constant1,
            Wrt2,
            Constant2,
            errcode,
            message_buffer,
            buffer_length,
        )
    }

    pub unsafe fn AbstractState_second_partial_deriv(
        &self,
        handle: ::core::ffi::c_long,
        Of1: ::core::ffi::c_long,
        Wrt1: ::core::ffi::c_long,
        Constant1: ::core::ffi::c_long,
        Wrt2: ::core::ffi::c_long,
        Constant2: ::core::ffi::c_long,
        errcode: *mut ::core::ffi::c_long,
        message_buffer: *mut ::core::ffi::c_char,
        buffer_length: ::core::ffi::c_long,
    ) -> f64 {
        AbstractState_second_partial_deriv(
            handle,
            Of1,
            Wrt1,
            Constant1,
            Wrt2,
            Constant2,
            errcode,
            message_buffer,
            buffer_length,
        )
    }

    pub unsafe fn AbstractState_first_two_phase_deriv_splined(
        &self,
        handle: ::core::ffi::c_long,
        Of: ::core::ffi::c_long,
        Wrt: ::core::ffi::c_long,
        Constant: ::core::ffi::c_long,
        x_end: f64,
        errcode: *mut ::core::ffi::c_long,
        message_buffer: *mut ::core::ffi::c_char,
        buffer_length: ::core::ffi::c_long,
    ) -> f64 {
        AbstractState_first_two_phase_deriv_splined(
            handle,
            Of,
            Wrt,
            Constant,
            x_end,
            errcode,
            message_buffer,
            buffer_length,
        )
    }

    pub unsafe fn AbstractState_first_two_phase_deriv(
        &self,
        handle: ::core::ffi::c_long,
        Of: ::core::ffi::c_long,
        Wrt: ::core::ffi::c_long,
        Constant: ::core::ffi::c_long,
        errcode: *mut ::core::ffi::c_long,
        message_buffer: *mut ::core::ffi::c_char,
        buffer_length: ::core::ffi::c_long,
    ) -> f64 {
        AbstractState_first_two_phase_deriv(
            handle,
            Of,
            Wrt,
            Constant,
            errcode,
            message_buffer,
            buffer_length,
        )
    }

    pub unsafe fn AbstractState_update_and_common_out(
        &self,
        handle: ::core::ffi::c_long,
        input_pair: ::core::ffi::c_long,
        value1: *const f64,
        value2: *const f64,
        length: ::core::ffi::c_long,
        T: *mut f64,
        p: *mut f64,
        rhomolar: *mut f64,
        hmolar: *mut f64,
        smolar: *mut f64,
        errcode: *mut ::core::ffi::c_long,
        message_buffer: *mut ::core::ffi::c_char,
        buffer_length: ::core::ffi::c_long,
    ) {
        AbstractState_update_and_common_out(
            handle,
            input_pair,
            value1,
            value2,
            length,
            T,
            p,
            rhomolar,
            hmolar,
            smolar,
            errcode,
            message_buffer,
            buffer_length,
        )
    }

    pub unsafe fn AbstractState_update_and_1_out(
        &self,
        handle: ::core::ffi::c_long,
        input_pair: ::core::ffi::c_long,
        value1: *const f64,
        value2: *const f64,
        length: ::core::ffi::c_long,
        output: ::core::ffi::c_long,
        out: *mut f64,
        errcode: *mut ::core::ffi::c_long,
        message_buffer: *mut ::core::ffi::c_char,
        buffer_length: ::core::ffi::c_long,
    ) {
        AbstractState_update_and_1_out(
            handle,
            input_pair,
            value1,
            value2,
            length,
            output,
            out,
            errcode,
            message_buffer,
            buffer_length,
        )
    }

    pub unsafe fn AbstractState_update_and_5_out(
        &self,
        handle: ::core::ffi::c_long,
        input_pair: ::core::ffi::c_long,
        value1: *const f64,
        value2: *const f64,
        length: ::core::ffi::c_long,
        outputs: *mut ::core::ffi::c_long,
        out1: *mut f64,
        out2: *mut f64,
        out3: *mut f64,
        out4: *mut f64,
        out5: *mut f64,
        errcode: *mut ::core::ffi::c_long,
        message_buffer: *mut ::core::ffi::c_char,
        buffer_length: ::core::ffi::c_long,
    ) {
        AbstractState_update_and_5_out(
            handle,
            input_pair,
            value1,
            value2,
            length,
            outputs,
            out1,
            out2,
            out3,
            out4,
            out5,
            errcode,
            message_buffer,
            buffer_length,
        )
    }

    pub unsafe fn AbstractState_set_binary_interaction_double(
        &self,
        handle: ::core::ffi::c_long,
        i: ::core::ffi::c_long,
        j: ::core::ffi::c_long,
        parameter: *const ::core::ffi::c_char,
        value: f64,
        errcode: *mut ::core::ffi::c_long,
        message_buffer: *mut ::core::ffi::c_char,
        buffer_length: ::core::ffi::c_long,
    ) {
        AbstractState_set_binary_interaction_double(
            handle,
            i,
            j,
            parameter,
            value,
            errcode,
            message_buffer,
            buffer_length,
        )
    }

    pub unsafe fn AbstractState_set_cubic_alpha_C(
        &self,
        handle: ::core::ffi::c_long,
        i: ::core::ffi::c_long,
        parameter: *const ::core::ffi::c_char,
        c1: f64,
        c2: f64,
        c3: f64,
        errcode: *mut ::core::ffi::c_long,
        message_buffer: *mut ::core::ffi::c_char,
        buffer_length: ::core::ffi::c_long,
    ) {
        AbstractState_set_cubic_alpha_C(
            handle,
            i,
            parameter,
            c1,
            c2,
            c3,
            errcode,
            message_buffer,
            buffer_length,
        )
    }

    pub unsafe fn AbstractState_set_fluid_parameter_double(
        &self,
        handle: ::core::ffi::c_long,
        i: ::core::ffi::c_long,
        parameter: *const ::core::ffi::c_char,
        value: f64,
        errcode: *mut ::core::ffi::c_long,
        message_buffer: *mut ::core::ffi::c_char,
        buffer_length: ::core::ffi::c_long,
    ) {
        AbstractState_set_fluid_parameter_double(
            handle,
            i,
            parameter,
            value,
            errcode,
            message_buffer,
            buffer_length,
        )
    }

    pub unsafe fn AbstractState_build_phase_envelope(
        &self,
        handle: ::core::ffi::c_long,
        level: *const ::core::ffi::c_char,
        errcode: *mut ::core::ffi::c_long,
        message_buffer: *mut ::core::ffi::c_char,
        buffer_length: ::core::ffi::c_long,
    ) {
        AbstractState_build_phase_envelope(handle, level, errcode, message_buffer, buffer_length)
    }

    pub unsafe fn AbstractState_get_phase_envelope_data(
        &self,
        handle: ::core::ffi::c_long,
        length: ::core::ffi::c_long,
        T: *mut f64,
        p: *mut f64,
        rhomolar_vap: *mut f64,
        rhomolar_liq: *mut f64,
        x: *mut f64,
        y: *mut f64,
        errcode: *mut ::core::ffi::c_long,
        message_buffer: *mut ::core::ffi::c_char,
        buffer_length: ::core::ffi::c_long,
    ) {
        AbstractState_get_phase_envelope_data(
            handle,
            length,
            T,
            p,
            rhomolar_vap,
            rhomolar_liq,
            x,
            y,
            errcode,
            message_buffer,
            buffer_length,
        )
    }

    pub unsafe fn AbstractState_get_phase_envelope_data_checkedMemory(
        &self,
        handle: ::core::ffi::c_long,
        length: ::core::ffi::c_long,
        maxComponents: ::core::ffi::c_long,
        T: *mut f64,
        p: *mut f64,
        rhomolar_vap: *mut f64,
        rhomolar_liq: *mut f64,
        x: *mut f64,
        y: *mut f64,
        actual_length: *mut ::core::ffi::c_long,
        actual_components: *mut ::core::ffi::c_long,
        errcode: *mut ::core::ffi::c_long,
        message_buffer: *mut ::core::ffi::c_char,
        buffer_length: ::core::ffi::c_long,
    ) {
        AbstractState_get_phase_envelope_data_checkedMemory(
            handle,
            length,
            maxComponents,
            T,
            p,
            rhomolar_vap,
            rhomolar_liq,
            x,
            y,
            actual_length,
            actual_components,
            errcode,
            message_buffer,
            buffer_length,
        )
    }

    pub unsafe fn AbstractState_build_spinodal(
        &self,
        handle: ::core::ffi::c_long,
        errcode: *mut ::core::ffi::c_long,
        message_buffer: *mut ::core::ffi::c_char,
        buffer_length: ::core::ffi::c_long,
    ) {
        AbstractState_build_spinodal(handle, errcode, message_buffer, buffer_length)
    }

    pub unsafe fn AbstractState_get_spinodal_data(
        &self,
        handle: ::core::ffi::c_long,
        length: ::core::ffi::c_long,
        tau: *mut f64,
        delta: *mut f64,
        M1: *mut f64,
        errcode: *mut ::core::ffi::c_long,
        message_buffer: *mut ::core::ffi::c_char,
        buffer_length: ::core::ffi::c_long,
    ) {
        AbstractState_get_spinodal_data(
            handle,
            length,
            tau,
            delta,
            M1,
            errcode,
            message_buffer,
            buffer_length,
        )
    }

    pub unsafe fn AbstractState_all_critical_points(
        &self,
        handle: ::core::ffi::c_long,
        length: ::core::ffi::c_long,
        T: *mut f64,
        p: *mut f64,
        rhomolar: *mut f64,
        stable: *mut ::core::ffi::c_long,
        errcode: *mut ::core::ffi::c_long,
        message_buffer: *mut ::core::ffi::c_char,
        buffer_length: ::core::ffi::c_long,
    ) {
        AbstractState_all_critical_points(
            handle,
            length,
            T,
            p,
            rhomolar,
            stable,
            errcode,
            message_buffer,
            buffer_length,
        )
    }

    pub unsafe fn AbstractState_keyed_output_satState(
        &self,
        handle: ::core::ffi::c_long,
        saturated_state: *const ::core::ffi::c_char,
        param: ::core::ffi::c_long,
        errcode: *mut ::core::ffi::c_long,
        message_buffer: *mut ::core::ffi::c_char,
        buffer_length: ::core::ffi::c_long,
    ) -> f64 {
        AbstractState_keyed_output_satState(
            handle,
            saturated_state,
            param,
            errcode,
            message_buffer,
            buffer_length,
        )
    }

    pub unsafe fn AbstractState_backend_name(
        &self,
        handle: ::core::ffi::c_long,
        backend: *mut ::core::ffi::c_char,
        errcode: *mut ::core::ffi::c_long,
        message_buffer: *mut ::core::ffi::c_char,
        buffer_length: ::core::ffi::c_long,
    ) {
        AbstractState_backend_name(handle, backend, errcode, message_buffer, buffer_length)
    }

    pub unsafe fn AbstractState_fluid_param_string(
        &self,
        handle: ::core::ffi::c_long,
        param: *const ::core::ffi::c_char,
        return_buffer: *mut ::core::ffi::c_char,
        return_buffer_length: ::core::ffi::c_long,
        errcode: *mut ::core::ffi::c_long,
        message_buffer: *mut ::core::ffi::c_char,
        buffer_length: ::core::ffi::c_long,
    ) {
        AbstractState_fluid_param_string(
            handle,
            param,
            return_buffer,
            return_buffer_length,
            errcode,
            message_buffer,
            buffer_length,
        )
    }

    pub unsafe fn AbstractState_phase(
        &self,
        handle: ::core::ffi::c_long,
        errcode: *mut ::core::ffi::c_long,
        message_buffer: *mut ::core::ffi::c_char,
        buffer_length: ::core::ffi::c_long,
    ) -> ::core::ffi::c_int {
        AbstractState_phase(handle, errcode, message_buffer, buffer_length)
    }

    pub unsafe fn AbstractState_saturated_liquid_keyed_output(
        &self,
        handle: ::core::ffi::c_long,
        param: ::core::ffi::c_long,
        errcode: *mut ::core::ffi::c_long,
        message_buffer: *mut ::core::ffi::c_char,
        buffer_length: ::core::ffi::c_long,
    ) -> f64 {
        AbstractState_saturated_liquid_keyed_output(
            handle,
            param,
            errcode,
            message_buffer,
            buffer_length,
        )
    }

    pub unsafe fn AbstractState_saturated_vapor_keyed_output(
        &self,
        handle: ::core::ffi::c_long,
        param: ::core::ffi::c_long,
        errcode: *mut ::core::ffi::c_long,
        message_buffer: *mut ::core::ffi::c_char,
        buffer_length: ::core::ffi::c_long,
    ) -> f64 {
        AbstractState_saturated_vapor_keyed_output(
            handle,
            param,
            errcode,
            message_buffer,
            buffer_length,
        )
    }

    pub unsafe fn add_fluids_as_JSON(
        &self,
        backend: *const ::core::ffi::c_char,
        fluidstring: *const ::core::ffi::c_char,
        errcode: *mut ::core::ffi::c_long,
        message_buffer: *mut ::core::ffi::c_char,
        buffer_length: ::core::ffi::c_long,
    ) {
        add_fluids_as_JSON(backend, fluidstring, errcode, message_buffer, buffer_length)
    }

    pub unsafe fn C_is_valid_fluid_string(
        &self,
        fluidName: *const ::core::ffi::c_char,
    ) -> ::core::ffi::c_int {
        C_is_valid_fluid_string(fluidName)
    }

    pub unsafe fn C_extract_backend(
        &self,
        fluid_string: *const ::core::ffi::c_char,
        backend: *mut ::core::ffi::c_char,
        backend_length: ::core::ffi::c_long,
        fluid: *mut ::core::ffi::c_char,
        fluid_length: ::core::ffi::c_long,
    ) -> ::core::ffi::c_int {
        C_extract_backend(fluid_string, backend, backend_length, fluid, fluid_length)
    }
}
